### ISSUE TITLE
SUGGESTION #1: Attack animation could be faster

### ISSUE THREAD

**Issue by SullivanStobo** [lawlbit/Wizards_Pub_Crawl#137] opened 2019-01-09 21:45 UTC
At the moment attacking (by pressing space) feels very slow and unresponsive. Speeding the animation up could fix this. Also locking player movement during this animation would make sense.

**Comment by SullivanStobo** [comment] 2019-01-09 21:55
To add to this, clicking to attack would also be nice. Unless there is other plans for what clicking does.

**Comment by SusanSuY** [comment] 2019-01-28 17:09
Duplicate of issue #88 for attack animation speed. Clicking to attack is under consideration, but low priority.

**Comment by lawlbit** [comment] 2019-03-22 20:36
Closing as the animation lag has been addressed.

**Closed by lawlbit** 2019-03-22 20:36 UTC
Labels: P3: Low Priority
